name: Trunk
on:
  push:
    tags:
      - '.*'

jobs:
  release:
    name: Release
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: xcode-select
      run: sudo xcode-select --switch '/Applications/Xcode_10.3.app'
    - name: Push
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: pod trunk push
